<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserTest extends TestCase
{
	use DatabaseMigrations;


	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/**
	 * A basic test example.
	 * @test
	 * @return void
	 */
	public function signUpUser()
	{
		$this->assertTrue(true);
	}
}
