<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserTest extends TestCase
{
	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/**
     * A basic test example.
     * @test
     * @return void
     */
    public function addUser()
    {
        $this->assertTrue(true);
    }
}
